info:
  contact: {}
  description: API Server for Qoinify application
  title: Qoinify API
  version: "1.0"
paths:
  /api/order/:
    post:
      consumes:
      - application/json
      description: Places an order on the market or a limit order
      parameters:
      - description: Market
        in: body
        name: market
        required: true
        schema:
          type: string
      - description: Type of the order (MARKET or LIMIT)
        in: body
        name: type
        required: true
        schema:
          type: string
      - description: Direction of the order (BUY или SELL)
        in: body
        name: bid
        required: true
        schema:
          type: boolean
      - description: Price (only for limit order)
        in: body
        name: price
        schema:
          type: string
      - description: Volume
        in: body
        name: size
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses: {}
      summary: order
      tags:
      - Orders
  /api/ping/:
    get:
      responses:
        "200":
          description: pong
          schema:
            type: string
      summary: ping
  /orderbook/{market}:
    get:
      description: Get the aggregated bid and ask orders for a market
      parameters:
      - description: Market name
        in: path
        name: market
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get orderbook data for a market
      tags:
      - orderbook
  /orders/{id}:
    delete:
      description: Deletes an order with the specified id
      parameters:
      - description: ID order
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: order deleted
          schema:
            type: string
        "400":
          description: Invalid order id
          schema:
            type: string
        "404":
          description: Order not found
          schema:
            type: string
        "500":
          description: Internal server error
          schema:
            type: string
      summary: Delete order
      tags:
      - Orders
swagger: "2.0"
